name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.3.0-dev.4
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  clock: ^1.1.1
  x509: ^0.2.3
  jose: ^0.3.4
  dotenv: ^4.1.0
  openid_client: ^0.4.7
  firebase_dart: ^1.0.11
  path: ^1.8.3
  meta: ^1.9.1
  http: ^1.1.0
  crypto_keys: ^0.3.0+1
  collection: ^1.17.1
  gcloud: ^0.8.10
  firebaseapis: ^0.1.2
  snapshot: ^0.2.5
  _discoveryapis_commons: ^1.0.6
  googleapis: ^11.4.0

dev_dependencies:
  test: ^1.24.5
  fake_async: ^1.3.1
  lints: ^2.1.1
  mockito: ^5.4.2

dependency_overrides:
  http: ^1.1.0

false_secrets:
 - /lib/src/testing.dart 